/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author florm
 */
public class VistaEscolaridad extends javax.swing.JFrame {

    /**
     * Creates new form VistaEscolaridad
     */
    public VistaEscolaridad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        entradaIdEscuela = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        entradaEscolaridad = new javax.swing.JTextField();
        entradaNombEscuela = new javax.swing.JTextField();
        grado = new javax.swing.JTextField();
        nombreProf = new javax.swing.JTextField();
        telfProfesor = new javax.swing.JTextField();
        dirEscuela = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        labelTotalRegistrad = new javax.swing.JLabel();
        Total_de_Registrados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Beneficiario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 400, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Id Escuela");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Escolaridad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        jLabel4.setText("Nombre Escuela");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jLabel5.setText("Grado");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jLabel6.setText("Nombre Profesor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        jLabel7.setText("Telefono Profesor");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));
        jPanel1.add(entradaIdEscuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 100, 30));

        jLabel8.setText("Direccion Escuela");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));
        jPanel1.add(entradaEscolaridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 100, 30));
        jPanel1.add(entradaNombEscuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 100, 30));
        jPanel1.add(grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 110, 30));
        jPanel1.add(nombreProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 100, 30));
        jPanel1.add(telfProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 100, 30));
        jPanel1.add(dirEscuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 110, 30));

        btnGuardar.setText("Guardar");
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Escuela", "Escolaridad", "Nombre Escuela", "Grado", "Nombre Profesor", "Telefono Profesor", "Direccion Escuela"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 840, 140));

        btnConsultar.setText("Consultar");
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, -1));
        jPanel1.add(labelTotalRegistrad, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, -1, 20));
        jPanel1.add(Total_de_Registrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 70, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEscolaridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEscolaridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEscolaridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEscolaridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEscolaridad().setVisible(true);
            }
        });
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public void setBtnGuardar(JButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    public JTextField getDirEscuela() {
        return dirEscuela;
    }

    public void setDirEscuela(JTextField dirEscuela) {
        this.dirEscuela = dirEscuela;
    }

    public JTextField getEntradaEscolaridad() {
        return entradaEscolaridad;
    }

    public void setEntradaEscolaridad(JTextField entradaEscolaridad) {
        this.entradaEscolaridad = entradaEscolaridad;
    }

    public JTextField getEntradaIdEscuela() {
        return entradaIdEscuela;
    }

    public void setEntradaIdEscuela(JTextField entradaIdEscuela) {
        this.entradaIdEscuela = entradaIdEscuela;
    }

    public JTextField getEntradaNombEscuela() {
        return entradaNombEscuela;
    }

    public void setEntradaNombEscuela(JTextField entradaNombEscuela) {
        this.entradaNombEscuela = entradaNombEscuela;
    }

    public JTextField getGrado() {
        return grado;
    }

    public void setGrado(JTextField grado) {
        this.grado = grado;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextField getNombreProf() {
        return nombreProf;
    }

    public void setNombreProf(JTextField nombreProf) {
        this.nombreProf = nombreProf;
    }

    public JTextField getTelfProfesor() {
        return telfProfesor;
    }

    public void setTelfProfesor(JTextField telfProfesor) {
        this.telfProfesor = telfProfesor;
    }

    public JButton getBtnConsultar() {
        return btnConsultar;
    }

    public void setBtnConsultar(JButton btnConsultar) {
        this.btnConsultar = btnConsultar;
    }

    public JLabel getTotal_de_Registrados() {
        return Total_de_Registrados;
    }

    public void setTotal_de_Registrados(JLabel Total_de_Registrados) {
        this.Total_de_Registrados = Total_de_Registrados;
    }

    public JLabel getLabelTotalRegistrad() {
        return labelTotalRegistrad;
    }

    public void setLabelTotalRegistrad(JLabel labelTotalRegistrad) {
        this.labelTotalRegistrad = labelTotalRegistrad;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Total_de_Registrados;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField dirEscuela;
    private javax.swing.JTextField entradaEscolaridad;
    private javax.swing.JTextField entradaIdEscuela;
    private javax.swing.JTextField entradaNombEscuela;
    private javax.swing.JTextField grado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelTotalRegistrad;
    private javax.swing.JTextField nombreProf;
    private javax.swing.JTextField telfProfesor;
    // End of variables declaration//GEN-END:variables
}
